In [2]:
import numpy as np
import tensorflow as tf
print(tf.__version__)

1.1.0


In [2]:
# example usage of tf.tile. 
# Aim: Our tensor a is 3 dimensional in its last dimension.  We call its first dimension the batch dimension.
# For each batch, we want to append a constant vector to all vectors of that batch (go from a to z in output below)

a=tf.constant([[[3,2,1],[7,8,9],[1,1,1]],
               [[0,0,0],[1,1,1],[1,1,1]], 
               [[2,2,2],[3,3,3],[1,1,1]], 
               [[4,4,4],[5,5,5],[1,1,1]]])

# 4 vectors to append, for 4 different batches
y=tf.constant([[-5,-5,-5,-5],[-7,-7,-7,-7],[-9,-9,-9,-9],[-11,-11,-11,-9]])
# make copies of those vectors with tf.tile
y=tf.tile(y,[1,tf.shape(a)[1]])
# reshape them, so that they can be appended
y=tf.reshape(y,[tf.shape(a)[0],tf.shape(a)[1],-1])
# append
z=tf.concat([a,y],axis=2)

with tf.Session() as sess:
    print("a=")
    print(sess.run(a))
    print("a.shape={}".format(a.shape))
    print("y=")
    print(sess.run(y))
    print("z=")
    print(sess.run(z))

a=
[[[3 2 1]
  [7 8 9]
  [1 1 1]]

 [[0 0 0]
  [1 1 1]
  [1 1 1]]

 [[2 2 2]
  [3 3 3]
  [1 1 1]]

 [[4 4 4]
  [5 5 5]
  [1 1 1]]]
a.shape=(4, 3, 3)
y=
[[[ -5  -5  -5  -5]
  [ -5  -5  -5  -5]
  [ -5  -5  -5  -5]]

 [[ -7  -7  -7  -7]
  [ -7  -7  -7  -7]
  [ -7  -7  -7  -7]]

 [[ -9  -9  -9  -9]
  [ -9  -9  -9  -9]
  [ -9  -9  -9  -9]]

 [[-11 -11 -11  -9]
  [-11 -11 -11  -9]
  [-11 -11 -11  -9]]]
z=
[[[  3   2   1  -5  -5  -5  -5]
  [  7   8   9  -5  -5  -5  -5]
  [  1   1   1  -5  -5  -5  -5]]

 [[  0   0   0  -7  -7  -7  -7]
  [  1   1   1  -7  -7  -7  -7]
  [  1   1   1  -7  -7  -7  -7]]

 [[  2   2   2  -9  -9  -9  -9]
  [  3   3   3  -9  -9  -9  -9]
  [  1   1   1  -9  -9  -9  -9]]

 [[  4   4   4 -11 -11 -11  -9]
  [  5   5   5 -11 -11 -11  -9]
  [  1   1   1 -11 -11 -11  -9]]]


In [3]:
# example usage of a mask tensor
tensor = tf.constant(np.array([[1, 2, 3],[4, 5, 6]]), dtype=tf.float32)
mask = tf.constant(np.array([[True, False, True],[True,True,False]]))

with tf.Session() as sess:
    print("---Tensor")
    print(sess.run(tensor))
    print("---Mask")
    print(sess.run(mask))
    print("---tensor*tf.cast(mask,dtype=tf.float32)")
    print(sess.run(tensor*tf.cast(mask,dtype=tf.float32)))
    print("---tf.boolean_mask(tensor,mask)")
    print(sess.run(tf.boolean_mask(tensor,mask)))

---Tensor
[[ 1.  2.  3.]
 [ 4.  5.  6.]]
---Mask
[[ True False  True]
 [ True  True False]]
---tensor*tf.cast(mask,dtype=tf.float32)
[[ 1.  0.  3.]
 [ 4.  5.  0.]]
---tf.boolean_mask(tensor,mask)
[ 1.  3.  4.  5.]


In [13]:
# Using our knowledge about tf tile to append a sentinel vector (go from a to z in output below)
a=tf.constant([[[1,0,0,0],[2,0,0,0],[3,0,0,0]],[[-1,0,0,0],[-2,0,0,0],[-3,0,0,0]]])
b=tf.constant([7,7,7,7])
b=tf.tile(b,tf.shape(a)[0:1])
b=tf.reshape(b,(-1,1,tf.shape(a)[2]))
z=tf.concat([a,b],axis=1)
print("a={}".format(a))
print("b={}".format(b))

with tf.Session() as sess:
    print("a")
    print(sess.run(a))
    print("b")
    print(sess.run(b))
    print("z")
    print(sess.run(z))

a=Tensor("Const_15:0", shape=(2, 3, 4), dtype=int32)
b=Tensor("Reshape_7:0", shape=(?, 1, ?), dtype=int32)
a
[[[ 1  0  0  0]
  [ 2  0  0  0]
  [ 3  0  0  0]]

 [[-1  0  0  0]
  [-2  0  0  0]
  [-3  0  0  0]]]
b
[[[7 7 7 7]]

 [[7 7 7 7]]]
z
[[[ 1  0  0  0]
  [ 2  0  0  0]
  [ 3  0  0  0]
  [ 7  7  7  7]]

 [[-1  0  0  0]
  [-2  0  0  0]
  [-3  0  0  0]
  [ 7  7  7  7]]]


In [25]:
#Another example needed for sentinel implementation
a=tf.constant([[1,1,0,0],[1,0,0,0]],dtype=tf.float32)
b=tf.constant([0],dtype=tf.float32)
b=tf.tile(b,[tf.shape(a)[0]])
print(b.shape)
print(a.shape)
b=tf.reshape(b,(tf.shape(a)[0],1))
z=tf.concat([a,b],axis=1)
with tf.Session() as sess:
    print("z")
    print(sess.run(z))


(?,)
(2, 4)
z
[[ 1.  1.  0.  0.  0.]
 [ 1.  0.  0.  0.  0.]]


In [5]:
# In the code of the DCN_model, adding a sentinel could look like this (not yet implemented)
#logging.info("q_outputs={}".format(q_outputs))
#q_sentinel = tf.get_variable("q_sentinel", (rnn_size,), initializer=tf.contrib.layers.xavier_initializer())
#q_sentinel = tf.tile(q_sentinel, tf.shape(q_outputs)[0:1])
#q_sentinel = tf.reshape(q_sentinel, (-1, 1, tf.shape(q_outputs)[2]))
#Qprime = tf.concat([q_outputs, q_sentinel], axis=1)

In [20]:
# example usage of softmax
a=tf.constant([[[1,0,2,0],[2,0,3,0],[3,0,4,0]],[[5,0,6,0],[6,0,7,0],[7,0,8,0]]],dtype='float32')

with tf.Session() as sess:
    print(sess.run(a))
    print(sess.run(tf.nn.softmax(a)))
    print(sess.run(tf.nn.softmax(tf.transpose(a,[0,2,1]))))
#=>softmax is row wise

[[[ 1.  0.  2.  0.]
  [ 2.  0.  3.  0.]
  [ 3.  0.  4.  0.]]

 [[ 5.  0.  6.  0.]
  [ 6.  0.  7.  0.]
  [ 7.  0.  8.  0.]]]
[[[  2.24515244e-01   8.25945437e-02   6.10295713e-01   8.25945437e-02]
  [  2.50692427e-01   3.39275263e-02   6.81452632e-01   3.39275263e-02]
  [  2.61927158e-01   1.30405845e-02   7.11991787e-01   1.30405845e-02]]

 [[  2.67970264e-01   1.80556939e-03   7.28418648e-01   1.80556939e-03]
  [  2.68583328e-01   6.65751519e-04   7.30085194e-01   6.65751519e-04]
  [  2.68809587e-01   2.45122617e-04   7.30700195e-01   2.45122617e-04]]]
[[[ 0.09003057  0.24472848  0.66524094]
  [ 0.33333334  0.33333334  0.33333334]
  [ 0.09003057  0.24472848  0.66524094]
  [ 0.33333334  0.33333334  0.33333334]]

 [[ 0.09003057  0.24472848  0.66524094]
  [ 0.33333334  0.33333334  0.33333334]
  [ 0.09003057  0.24472848  0.66524094]
  [ 0.33333334  0.33333334  0.33333334]]]


In [7]:
# gather_nd example
logits = tf.constant([[[10.0, 10.0, 20.0, 20.0],
                      [11.0, 10.0, 10.0, 30.0],
                      [12.0, 10.0, 10.0, 20.0],
                      [13.0, 10.0, 10.0, 20.0]],
                     [[14.0, 11.0, 21.0, 31.0],
                      [15.0, 11.0, 11.0, 21.0],
                      [16.0, 11.0, 11.0, 21.0],
                      [17.0, 11.0, 11.0, 21.0]]])

# pick vector 1 in batch 0, then vec 3 in batch 1 then vec 1 in batch 1
indices = tf.constant([[0,1],[1,3],[1,1]]) 

result = tf.gather_nd(logits, indices)
with tf.Session() as sess:
    print("------------logits")
    print(sess.run(logits))
    print("------------result")
    print(sess.run(result))


------------logits
[[[ 10.  10.  20.  20.]
  [ 11.  10.  10.  30.]
  [ 12.  10.  10.  20.]
  [ 13.  10.  10.  20.]]

 [[ 14.  11.  21.  31.]
  [ 15.  11.  11.  21.]
  [ 16.  11.  11.  21.]
  [ 17.  11.  11.  21.]]]
------------result
[[ 11.  10.  10.  30.]
 [ 17.  11.  11.  21.]
 [ 15.  11.  11.  21.]]


In [8]:
#tf range is simple :)
with tf.Session() as sess:
    print(sess.run(tf.range(0,2,1))) #start, stop, step
    print(sess.run(tf.range(-1,7,3)))

[0 1]
[-1  2  5]


In [9]:
# Example code for picking us and ue from U using tf.gather_nd() (see DCN_model.py)
logits = tf.constant([[[10.0, 10.0, 20.0, 20.0],
                      [11.0, 10.0, 10.0, 30.0],
                      [12.0, 10.0, 10.0, 20.0],
                      [13.0, 10.0, 10.0, 20.0]],
                     [[14.0, 11.0, 21.0, 31.0],
                      [15.0, 11.0, 11.0, 21.0],
                      [16.0, 11.0, 11.0, 21.0],
                      [17.0, 11.0, 11.0, 21.0]],
                     [[-1, 11.0, 21.0, 31.0],
                      [-2, 11.0, 11.0, 21.0],
                      [-3, 11.0, 11.0, 21.0],
                      [-4, 11.0, 11.0, 21.0]]])

# in theses 3 batches of logits, I want to pick vec 0 in batch 0, vec 3 in batch 1, vec 2 in batch 2
pick = tf.constant([0,3,2],dtype='int32') 
print(pick)
idx = tf.range(0,tf.shape(pick)[0],1)
n_idx = tf.stack([idx,pick],axis=1)

print(logits)

result = tf.gather_nd(logits, n_idx)

with tf.Session() as sess:
    print(10*"-"+"logits")
    print(sess.run(logits))
    print(10*"-"+"concat idx and pick")
    print(sess.run(tf.concat([idx,pick],axis=0)))
    print(10*"-"+"stack idx and pick to obtain n_idx")
    print(sess.run(n_idx))
    print(10*"-"+"access logits via the index array n_idx")
    print(sess.run(result))

Tensor("Const_10:0", shape=(3,), dtype=int32)
Tensor("Const_9:0", shape=(3, 4, 4), dtype=float32)
----------logits
[[[ 10.  10.  20.  20.]
  [ 11.  10.  10.  30.]
  [ 12.  10.  10.  20.]
  [ 13.  10.  10.  20.]]

 [[ 14.  11.  21.  31.]
  [ 15.  11.  11.  21.]
  [ 16.  11.  11.  21.]
  [ 17.  11.  11.  21.]]

 [[ -1.  11.  21.  31.]
  [ -2.  11.  11.  21.]
  [ -3.  11.  11.  21.]
  [ -4.  11.  11.  21.]]]
----------concat idx and pick
[0 1 2 0 3 2]
----------stack idx and pick to obtain n_idx
[[0 0]
 [1 3]
 [2 2]]
----------access logits via the index array n_idx
[[ 10.  10.  20.  20.]
 [ 17.  11.  11.  21.]
 [ -3.  11.  11.  21.]]


In [10]:
# map_fn example. Pretty near to what is needed for the HMN decoder
# Aim in this example: Each vector in U (along last dimension), should be mapped to its dot product with [2,0,1,0]
# but assume that we have to transpose U first and have to work with U_transpose=tf.transpose(U,[1,0,2])
U=tf.constant([[[1,4,3,0],[2,0,-1,0],[7,0,5,0]],[[-1,0,0,0],[-2,0,0,0],[-3,5,5,5]]], dtype='float32')
U_transpose=tf.transpose(U,[1,0,2])
print(U)
print(U_transpose)
proj = tf.constant([2,0,1,0],dtype='float32')
def funci(u_t,projo):
    return tf.reduce_sum(tf.multiply(u_t, projo),axis=1)
#fn = lambda u_t: tf.multiply(u_t, proj)
Utilde=tf.map_fn(lambda u_t: funci(u_t,proj), U_transpose, dtype=tf.float32)
print(Utilde.shape)
alpha = tf.transpose(Utilde,[1,0])
with tf.Session() as sess:
    print(10*"-"+"U")
    print(sess.run(U))
    print(10*"-"+"U_transpose")
    print(sess.run(U_transpose))
    print(10*"-"+"Utilde")
    print(sess.run(Utilde))
    print("-"*10+"tf.reshape(Utilde,[2,3])) fails to do the right thing!")
    print(sess.run(tf.reshape(Utilde,[2,3])))
    print("-"*10+"tf.transpose(Utilde,[1,0])) gives the desired result")
    print(sess.run(tf.transpose(Utilde,[1,0])))
    print("-"*10)
    print(sess.run(tf.argmax(alpha,1)))

Tensor("Const_11:0", shape=(2, 3, 4), dtype=float32)
Tensor("transpose_1:0", shape=(3, 2, 4), dtype=float32)
(3, 2)
----------U
[[[ 1.  4.  3.  0.]
  [ 2.  0. -1.  0.]
  [ 7.  0.  5.  0.]]

 [[-1.  0.  0.  0.]
  [-2.  0.  0.  0.]
  [-3.  5.  5.  5.]]]
----------U_transpose
[[[ 1.  4.  3.  0.]
  [-1.  0.  0.  0.]]

 [[ 2.  0. -1.  0.]
  [-2.  0.  0.  0.]]

 [[ 7.  0.  5.  0.]
  [-3.  5.  5.  5.]]]
----------Utilde
[[  5.  -2.]
 [  3.  -4.]
 [ 19.  -1.]]
----------tf.reshape(Utilde,[2,3])) fails to do the right thing!
[[  5.  -2.   3.]
 [ -4.  19.  -1.]]
----------tf.transpose(Utilde,[1,0])) gives the desired result
[[  5.   3.  19.]
 [ -2.  -4.  -1.]]
----------
[2 2]


In [11]:
# example usage of reduce_max, necessary for the HMN decoder
U=tf.constant([[1,2,3],[7,8,9]])
with tf.Session() as sess:
    print(sess.run(U))
    print(sess.run(tf.reduce_max(U,axis=1)))

[[1 2 3]
 [7 8 9]]
[3 9]
